# Generated by Django 4.0.4 on 2022-05-18 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrp', '0002_remove_basicinfo_id_basicinfo_cid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basicinfo',
            old_name='cid',
            new_name='candidateid',
        ),
    ]
