# Generated by Django 4.0.4 on 2022-05-20 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrp', '0003_rename_cid_basicinfo_candidateid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinfo',
            name='contact',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='ctc',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='qualifications',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='skills',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
