# Generated by Django 4.0.4 on 2022-05-21 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrp', '0004_alter_basicinfo_contact_alter_basicinfo_ctc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='filestorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='hrporal/media/')),
            ],
        ),
    ]
