# Generated by Django 4.0.4 on 2022-05-23 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrp', '0005_filestorage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='filestorage',
        ),
        migrations.AddField(
            model_name='basicinfo',
            name='file',
            field=models.FileField(blank=True, upload_to='pictures'),
        ),
    ]
