# Generated by Django 4.0.4 on 2022-06-15 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrp', '0006_delete_filestorage_basicinfo_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='consultanttable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('info', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='basicinfo',
            name='consultant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hrp.consultanttable'),
        ),
    ]
