# Generated by Django 4.0.4 on 2022-06-15 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrp', '0007_consultanttable_basicinfo_consultant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultanttable',
            name='info',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='consultanttable',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
