# Generated by Django 4.0.4 on 2022-06-15 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrp', '0008_alter_consultanttable_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinfo',
            name='file',
            field=models.FileField(null=True, upload_to='pictures'),
        ),
    ]
