# Generated by Django 4.0.4 on 2022-06-15 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrp', '0009_alter_basicinfo_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinfo',
            name='consultant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hrp.consultanttable'),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='pictures'),
        ),
    ]
