# Generated by Django 4.0.4 on 2022-06-15 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrp', '0010_alter_basicinfo_consultant_alter_basicinfo_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinfo',
            name='contact',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='ctc',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='qualifications',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='skills',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
