# Generated by Django 4.0.4 on 2022-06-15 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrp', '0011_alter_basicinfo_contact_alter_basicinfo_ctc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinfo',
            name='consultant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='table', to='hrp.consultanttable'),
        ),
    ]
