# Generated by Django 4.0.4 on 2022-06-15 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrp', '0014_alter_consultanttable_info_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='consultanttable',
            new_name='table',
        ),
    ]
