# Generated by Django 4.0.4 on 2022-06-16 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrp', '0016_remove_basicinfo_consultant_table_consultant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='table',
        ),
    ]
