# Generated by Django 4.0.4 on 2022-06-16 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrp', '0019_alter_basicinfo_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basicinfo',
            old_name='id',
            new_name='cid',
        ),
    ]
