# Generated by Django 4.0.4 on 2022-06-20 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrp', '0021_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='consultant',
        ),
        migrations.AddField(
            model_name='basicinfo',
            name='consultant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultant', to='hrp.table'),
        ),
    ]
