# Generated by Django 4.0.4 on 2022-06-22 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrp', '0023_alter_table_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='consultant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('info', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='basicinfo',
            name='consultant',
        ),
        migrations.DeleteModel(
            name='table',
        ),
        migrations.AddField(
            model_name='consultant',
            name='basic_consultant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='basic_consultant', to='hrp.basicinfo'),
        ),
    ]
