# Generated by Django 4.0.4 on 2022-06-22 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrp', '0024_consultant_remove_basicinfo_consultant_delete_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinfo',
            name='cid',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
