# Generated by Django 4.0.4 on 2022-06-22 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrp', '0025_alter_basicinfo_cid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinfo',
            name='cid',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
