# Generated by Django 4.0.4 on 2022-06-22 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrp', '0026_alter_basicinfo_cid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultant',
            name='basic_consultant',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='basic_consultant', to='hrp.basicinfo'),
        ),
    ]
