# Generated by Django 4.0.4 on 2022-06-22 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrp', '0027_alter_consultant_basic_consultant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultant',
            old_name='info',
            new_name='HR_name',
        ),
        migrations.RenameField(
            model_name='consultant',
            old_name='name',
            new_name='company_name',
        ),
        migrations.RemoveField(
            model_name='basicinfo',
            name='skills',
        ),
        migrations.AddField(
            model_name='consultant',
            name='HR_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
