# Generated by Django 4.0.4 on 2022-06-30 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrp', '0030_alter_basicinfo_contact_alter_consultant_hr_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicinfo',
            name='client_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
