# Generated by Django 4.0.4 on 2022-07-01 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrp', '0032_remove_basicinfo_current_job_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinfo',
            name='exp_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
