# Generated by Django 4.0.4 on 2022-07-02 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrp', '0034_alter_education_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
    ]
