# Generated by Django 4.0.4 on 2022-07-02 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrp', '0036_alter_education_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='year_of_passing',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
